"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-20

The initial schema is created directly from the SQLAlchemy metadata so it stays
in lock-step with ``app.models``. Subsequent schema changes MUST be added as
explicit, autogenerated Alembic revisions (see CLAUDE.md).
"""
from alembic import op

from app.database import Base
import app.models  # noqa: F401  (populate Base.metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
